# Generated by Django 6.0.2 on 2026-03-01 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('available_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'denomination',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_master',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('total_without_tax', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rounded_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_history',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productmaster')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.purchasehistory')),
            ],
            options={
                'db_table': 'purchase_item',
                'ordering': ('created_at',),
            },
        ),
    ]
