# Generated by Django 6.0.2 on 2026-03-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='change_given',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
