# Generated by Django 6.0.2 on 2026-03-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_purchasehistory_change_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='change_given',
            field=models.JSONField(default=dict),
        ),
    ]
