# Generated by Django 6.0.2 on 2026-03-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_purchasehistory_change_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='purchase_price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='unit_price',
            new_name='purchase_price',
        ),
    ]
